# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Term-Animation
version:      2.4
version_from: lib/Term/Animation.pm
installdirs:  site
requires:
    Curses:                        1.06

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
license: perl
